### ISSUE TITLE
Gracefully handle JSONDecodeError when reading PurpleAir Data

### ISSUE THREAD

**Issue by ianhoffman** [airq-dev/hazebot#135]
We get this every once in awhile:

```
Expecting ',' delimiter: line 1 column 5999899 (char 5999898)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/app/app/airq/celery.py", line 52, in __call__
    return self.run(*args, **kwargs)
  File "/home/app/app/airq/tasks.py", line 8, in models_sync
    models_sync()
  File "/home/app/app/airq/sync/__init__.py", line 33, in models_sync
    purpleair_sync()
  File "/home/app/app/airq/sync/purpleair.py", line 264, in purpleair_sync
    purpleair_data = _get_purpleair_data()
  File "/home/app/app/airq/sync/purpleair.py", line 41, in _get_purpleair_data
    results = resp.json().get("results", [])
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 5999899 (char 5999898)
```

The app can tolerate a partial failure for 30 minutes or so, the data just gets a bit stale, so this isn't a big issue. We should gracefully handle this error — probably still log an exception, but with a better message? Or we could log a warning and then log an exception later on in the sync job if the data is more than 30 minutes stale (or something like that).

**Comment by ianhoffman** [comment]
This has been fixed for awhile.
